//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : Main.cs
//  @ Date : 1/14/2011
//  @ Author : 
//
//


public class Main {
	private GameState state ;
	private GameWorldManager gameManager ;
	public GameMenu gameMenu ;
	public void init(){
	}
	public void loadContent(){
	}
	public void unloadContent(){
	}
	public void update(){
	}
	private void updateMedia(){
	}
}
