//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : GameMenu.cs
//  @ Date : 1/14/2011
//  @ Author : 
//
//
using System.Collections.Generic;
using System.IO;

using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Content;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;
using Microsoft.Xna.Framework.Input.Touch;

using PsychicNinja.Interface.Engine;
using PsychicNinja.Data.Util;
using PsychicNinja.Data.Object;
using PsychicNinja.Data.Object.Entity;
using PsychicNinja.Logic;
using System;
using PsychicNinja.Interface;

public class ChapterCompletionScreen : GameMenu
{
    //private static Rectangle position = new Rectangle(100, 60, 600, 360);
    private static Rectangle position = new Rectangle(0, 0, 800, 480);


    private static Texture2D completionScreenTexture;
    private static Texture2D replayLevelTexture;
    private static Texture2D nextLevelTexture;
    private static Texture2D titleScreenTexture;
    private static Texture2D chapterTexture;
    private static Texture2D completeTexture;
    private static Texture2D shine;
    private static SpriteFont newRecordFont;

    private Button replay;
    private Button toTitleScreen;

    private bool newRecord;
    private bool shineBarFinished;
    private bool showingTimes;

    View shineBar;
    View chapterLogo;
    View completeLogo;
    Emitter sparklesTop;
    Emitter sparklesBottom;

    static List<Texture2D> particleArt;

    TimeSpan completionTime;
    string completionTimeString;
    string RecordTimeString;



    Color glowColor;

    int increment = 3;
    int value = 185;

    public ChapterCompletionScreen(TimeSpan t, TimeSpan r, bool nr)
    {
        PersonalLoadContent();
        SetDrawFrame(position);
        drawTex = completionScreenTexture;

        this.animatedAlphaFadeIn(90);

        replay = new Button(new Rectangle(-450, 400, 250, 50), replayLevelTexture);
        toTitleScreen = new Button(new Rectangle(1000, 400, 500, 50), titleScreenTexture);
        chapterLogo = new View(new Rectangle(1200, 20, 456, 56), chapterTexture);
        completeLogo = new View(new Rectangle(-600, 90, 533, 56), completeTexture);
        shineBar = new View(new Rectangle(-100, 20, 100, 56), shine);

        replay.animatedFrameSlide(new Point(470, 0), 45, true);
        toTitleScreen.animatedFrameSlide(new Point(-720, 0), 45, true);
        chapterLogo.animatedFrameSlide(new Point(-1200, 0), 30, true);
        completeLogo.animatedFrameSlide(new Point(867, 0), 30, true);


        sparklesTop = new Emitter(new Rectangle(0, 0, 800, 1), new Vector2(0f, 1f), 0, 0.95, .04, 160, 150, particleArt);
        sparklesTop.drawInScreenCoordinates = true;
        sparklesTop.isEmitting = true;
        sparklesTop.particlesFade = true;

        sparklesBottom = new Emitter(new Rectangle(0, 479, 800, 1), new Vector2(0f, -1f), 0, 0.95, .04, 160, 150, particleArt);
        sparklesBottom.drawInScreenCoordinates = true;
        sparklesBottom.isEmitting = true;
        sparklesBottom.particlesFade = true;

        completionTime = t;
        completionTimeString = string.Format("{0:00}:{1:00}:{2:0000}", (int)completionTime.Minutes, (int)completionTime.Seconds, (int)completionTime.Milliseconds);

        RecordTimeString = string.Format("{0:00}:{1:00}:{2:0000}", (int)r.Minutes, (int)r.Seconds, (int)r.Milliseconds);

        shineBarFinished = false;
        showingTimes = false;
        newRecord = nr;

        glowColor = new Color(value, value, 0); 

        flag = GameMenuFlag.NoFlag;

        MusicManager.PlaySoundEffect(SoundEffects.levelComplete1);

        
        //Not sure why this doesnt work, but we'll need it eventually
        //System.IO.DirectoryInfo contentDir = new System.IO.DirectoryInfo("Level");
        //chapterFiles = contentDir.GetFiles();
    }

    private static void PersonalLoadContent()
    {
        newRecordFont = Content.Load<SpriteFont>("Motorwerk");
        completionScreenTexture = Content.Load<Texture2D>("chaptercompletebg");
        replayLevelTexture = Content.Load<Texture2D>("replay");
        titleScreenTexture = Content.Load<Texture2D>("ToTitlescreen2");
        shine = Content.Load<Texture2D>("shine thingy");

        chapterTexture = Content.Load<Texture2D>("chapter");
        completeTexture = Content.Load<Texture2D>("complete");

        particleArt = new List<Texture2D>();

        particleArt.Add(Content.Load<Texture2D>("NonInteractive/smallspark"));
        particleArt.Add(Content.Load<Texture2D>("NonInteractive/mediumspark"));

    }

    public override void Update() 
    {
        base.Update();
        //slick animations here
        chapterLogo.Update();
        completeLogo.Update();
        replay.Update();
        toTitleScreen.Update();

        if (showingTimes)
        {
            if (value > 255)
            {
                value = 255;
                increment = 0 - Math.Abs(increment);
            }
            else if (value < 170)
            {
                value = 170;
                increment = Math.Abs(increment);
            }
            else
                value += increment;
            glowColor = new Color(value, value, 0);
        }


        if(!completeLogo.isAnimating()){
            if (!shineBar.isAnimating()  && !shineBarFinished)
            {
                shineBarFinished = true;
                shineBar.animatedFrameSlide(new Point(900, 0), 60, false);
                MusicManager.PlaySoundEffect(SoundEffects.chapterClear);
                showingTimes = true;
            }
            else
                shineBar.Update();
            sparklesTop.Update();
            sparklesBottom.Update();
        }




    }

    public override void Draw(SpriteBatch spriteBatch)
    {
        base.Draw(spriteBatch);

        sparklesTop.Draw(spriteBatch);
        sparklesBottom.Draw(spriteBatch);

        chapterLogo.Draw(spriteBatch);
        completeLogo.Draw(spriteBatch);
        shineBar.Draw(spriteBatch);
        replay.Draw(spriteBatch);
        toTitleScreen.Draw(spriteBatch);


        if (showingTimes)
        {
            Color drawColor;
            if (newRecord)
            {
                drawColor = glowColor;
                spriteBatch.DrawString(newRecordFont, "A NEW RECORD!", new Vector2(200, 225), drawColor);
            }
            else
                drawColor = Color.White;

            spriteBatch.DrawString(CommandMenu.counterfont, "Final Stage Record Time:  " + RecordTimeString, new Vector2(10, 155), drawColor);
            spriteBatch.DrawString(CommandMenu.counterfont, "Final Stage Elapsed Time: " + completionTimeString, new Vector2(10, 195), drawColor);


        }
    }

    public override bool ProcessTouch(GestureSample gesture)
    {
        //base.ProcessInput(gesture);

        if (toTitleScreen.RespondsToGesture(gesture))
        {
            flag = GameMenuFlag.ToTitleScreen;
        }

        else if (replay.RespondsToGesture(gesture))
        {
            flag = GameMenuFlag.Replay;
        }

        return flag != GameMenuFlag.NoFlag;
    }
}
