//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : Untitled
//  @ File Name : MenuOptions.cs
//  @ Date : 1/14/2011
//  @ Author : 
//
//


public enum MenuOptions {
	ToChapterSelect,
	ToLevelSelect,
	ToOptions,
	BackToMain,
	BackToChapterSelect
}
